### ISSUE TITLE
create_collection no data 

### ISSUE THREAD

**Issue by ZhuJD-China** [onlyphantom/llm-python#8] opened 2023-07-10 07:42 UTC
#  https://docs.trychroma.com/embeddings
# create a Chroma vector store, by default operating purely in-memory
chroma_client = chromadb.Client()

# create a collection
chroma_collection = chroma_client.create_collection("newspieces")
# https://docs.trychroma.com/api-reference
print(chroma_collection.count())

documents = SimpleDirectoryReader('news').load_data()

index = GPTVectorStoreIndex.from_documents(documents, chroma_collection=chroma_collection)
print(chroma_collection.count())
print(chroma_collection.get()['documents'])
print(chroma_collection.get()['metadatas'])
output：
0
0
[]
[]

**Comment by onlyphantom** [comment] 2023-07-10 09:21
Thanks for the issue! What versions of these packages are you working on? Can you do a pip list?

**Comment by ZhuJD-China** [comment] 2023-07-10 09:44
python3.10
llama-index                   0.6.31
chromadb                      0.3.26

**Comment by ZhuJD-China** [comment] 2023-07-10 09:47
Chroma==0.2.0

**Comment by onlyphantom** [comment] 2023-07-10 13:08
@VanillaMacchiato can you try and reproduce? I'll see if I can get a fix out by end of week if so

**Comment by VanillaMacchiato** [comment] 2023-07-11 03:21
okay, I'll check it out

**Comment by VanillaMacchiato** [comment] 2023-07-11 07:21
I found the fix from an example in the documentation
https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/chroma_auto_retriever.html

Instead of 
```py
index = GPTVectorStoreIndex.from_documents(documents, chroma_collection=chroma_collection)
```

it is now
```py
vector_store = ChromaVectorStore(chroma_collection)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = GPTVectorStoreIndex.from_documents(documents, storage_context=storage_context)
```

**Comment by ZhuJD-China** [comment] 2023-07-11 14:49
This ok !
print(chroma_collection.count())
print(chroma_collection.get()['documents'])
print(chroma_collection.get()['metadatas'])


**but the During query time, the index uses Chroma to query for the top k not work.**

query_engine = index.as_query_engine()
r = query_engine.query("Who are the main exporters of Coal to China? What is the role of Indonesia in this?")
print(r)

**Comment by onlyphantom** [comment] 2023-07-11 23:27
Thanks for the fix @VanillaMacchiato 

> to query for the top k not work
@ZhuJD-China  I'm not sure I understand what "query for the top k not work?" means, can you elaborate?

Since the issue was resolved, I'll be closing this shortly, but feel free to open another issue discussing top k if you think its necessary? Have a great day!

**Closed by onlyphantom** 2023-07-11 23:27 UTC

**Comment by GitSyncPromedia** [comment] 2024-04-27 06:29
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
byte-ramble, @msrkp, @piapip, @nickatnight23, @1x-eng, @deadPix3l, @iprotoni, @natzuu, @alfheimrShiven, @uleeeeee, @s1dc0des, @tripplyons, @JohannesGitHub, @Mingkai-Li, @Troublor, @csmattjohnston, @yinkakun, @danicunhac, @Kair0s3, @hlbt, @alexanderattar, @tdergouzi, @goodcopybruh, @vijaykrishnavanshi, @Texnomic, @freekarma-dev, @aetherjs, @dpmabo, @helperShang, @ogty, @extremecoders-re, @nickkatsios, @yysung1123, @palcodes, @joseabraham, @2facedsquid, @AinuX, @tjwsoup, @0xhanh, @mhchia, @0xd403, @peterblockman, @cmboling, @lyftium, @HHHao-1, @joeblau, @Cnoe92, @0xnayan, @Robert-CPX, @rex5207
